all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
atom_type_prediction: false
batch_size: 12
bond_type_prediction: false
c_alpha_max_neighbors: 24
cache_path: /home/chengxi/PDBBind_carb_test/cache_RTMScoreFeature_Surface_PDBBIND_pocket_8A_all_esm3
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: /home/chengxi/data/work/CBS/SurfDock/data/eval_sample_dirs/surf_train
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: /home/chengxi/data/work/CBS/SurfDock-esm3/data/eval_sample_dirs/SurfDock_eval_samples/carb_train/test_samples_esmbedding/esm3_pdbbind_embeddings.pt
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
ligand_distance_prediction: false
ligand_embeddings_path: /home/chengxi/data/work/CBS/SurfDock/unimol/my_data/my_train_unimol_repr.pkl
limit_complexes: 0
log_dir: /home/chengxi/data/work/CBS/SurfDock/log_250504_glycan_ft_esm3
lr: 0.001
matching: true
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
mdn_dist_threshold_test: 5.0
mdn_dist_threshold_train: 7.0
mdn_dropout: 0.1
mdn_early_stop_patience: 30
model_type: surface_score_model
model_version: version3
n_epochs: 100
n_gaussians: 20
no_batch_norm: false
no_torsion: false
ns: 48
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 10
num_inference_complexes: 500
num_workers: 10
nv: 10
pin_memory: false
project: V3_PDBBind_ema_model_pocket_8A
receptor_radius: 15.0
remove_hs: true
residue_type_prediction: false
restart_dir: /home/chengxi/data/work/CBS/SurfDock/model_weights/docking_ret
restart_lr: null
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.33
run_name: project_V3_PDBBind_ema_model_pocket_8A_RunTime_2025_01_13_09_13_06_ns_48_nv_10_layer_batch_size_12_6
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 50
sigma_embed_dim: 32
skip_inference_freq: 0
split_test: /home/chengxi/data/work/CBS/SurfDock/data/splits/carb_all_test_pure_glycan
split_train: /home/chengxi/data/work/CBS/SurfDock/data/splits/carb_all_train_pure_glycan
split_val: /home/chengxi/data/work/CBS/SurfDock/data/splits/carb_all_vali_pure_glycan
surface_path: /home/chengxi/data/work/CBS/SurfDock/data/eval_sample_dirs/SurfDock_eval_samples/carb_train/test_samples_8A_surface/
test_sigma_intervals: false
topN: 1
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tr_sigma_max: 5.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
transformStyle: diffdock
use_ema: false
use_second_order_repr: false
val_inference_freq: 20
w_decay: 0.0
wandb: false
wandb_dir: wandb
